# functions definition block
# ###

# creates an object to manipulate the data source/s
createDataObject <- function(basedir='data') {

    url <- 'http://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip'

    keyfiles <- list(
        datafile       = sprintf('%s/data.zip', basedir),
        summary        = sprintf('%s/summarySCC_PM25.rds', basedir),
        classification = sprintf('%s/Source_Classification_Code.rds', basedir),
        processed      = sprintf('%s/processed.rds', basedir)
    )

    # get and transform the data if necessary
    getData <- function(...) {

        if (!all(file.exists(unlist(keyfiles)))) {

            if (file.exists(basedir)) {
                unlink(basedir, recursive=T)
            }

            dir.create(basedir)
            download.file(url, keyfiles$datafile, ...)
            unzip(keyfiles$datafile, exdir=basedir)

            summary <- readRDS(keyfiles$summary)[,-3]
            classif <- readRDS(keyfiles$classification)

            coal_combustion_filter <-
                grepl('Combustion', classif$SCC.Level.One) &
                grepl('Coal', classif$SCC.Level.Three)

            vehicle_filter <- grepl('Vehicle', classif$SCC.Level.Two)

            my_classif <- data.frame(
                SCC = classif$SCC,
                is_coal_combustion = coal_combustion_filter,
                is_motor_vehicle = vehicle_filter)

            processed <- merge(summary, my_classif)
            processed$fips <- as.integer(processed$fips)
            processed$type <- factor    (processed$type)

            saveRDS(processed[,-1], file=keyfiles$processed)
        }

        return(0)
    }

    # read processed data generated by getData
    loadData <- function() {
        data <- readRDS(keyfiles$processed)
        return(data)
    }

    list(getData = getData, loadData = loadData)
}

# do the plotting work
doAssignement <- function() {
    par(mfcol=c(1,1))
    hist(hpc$GlobalActivePower, col='red', xlab='Global Active Power (kilowatts)', main='Global Active Power')
}


# script block
# ###

# get data
hpc <- {
    dataobj <- createDataObject()
    dataobj$getData()
    dataobj$loadData()
}

# plot on screen device
#plot1()

# plot on png device
#png('plot1.png')
#plot1()
#dev.off()

# and... (╯°□°）╯︵ ┻━┻
# work finished better go for a walk
