# functions definition block
# ###

# creates an object to manipulate the data source/s
createDataObject <- function(basedir='data') {

    url <- 'http://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip'

    keyfiles <- list(
        datafile       = sprintf('%s/data.zip', basedir),
        summary        = sprintf('%s/summarySCC_PM25.rds', basedir),
        classification = sprintf('%s/Source_Classification_Code.rds', basedir),
        processed      = sprintf('%s/processed.rds', basedir)
    )

    # get and transform the data if necessary
    getData <- function(...) {

        if (!all(file.exists(unlist(keyfiles)))) {

            if (file.exists(basedir)) {
                unlink(basedir, recursive=T)
            }

            dir.create(basedir)
            download.file(url, keyfiles$datafile, ...)
            unzip(keyfiles$datafile, exdir=basedir)

            summary <- readRDS(keyfiles$summary)[,-3]
            classif <- readRDS(keyfiles$classification)

            coal_combustion_filter <-
                grepl('Combustion', classif$SCC.Level.One) &
                grepl('Coal', classif$SCC.Level.Three)

            vehicle_filter <- grepl('Vehicle', classif$SCC.Level.Two)

            my_classif <- data.frame(
                SCC = classif$SCC,
                is_coal_combustion = coal_combustion_filter,
                is_motor_vehicle = vehicle_filter)

            processed <- merge(summary, my_classif)
            processed$fips <- as.integer(processed$fips)
            processed$type <- factor    (processed$type)

            saveRDS(processed[,-1], file=keyfiles$processed)
        }

        return(0)
    }

    # read processed data generated by getData
    loadData <- function() {
        data <- readRDS(keyfiles$processed)
        return(data)
    }

    list(getData = getData, loadData = loadData)
}

# do the plotting work
doAssignement <- function(data) {

    agg_data <- data[data$year %in% seq(1999, 2008) & data$fips == 24510, c('Emissions', 'year')]
    agg_data <- aggregate(agg_data$Emissions/ 10e6, list(agg_data$year), sum)

    agg_table <- as.table(agg_data$x)
    dimnames(agg_table) <- list(agg_data$Group.1)

    par(mfcol=c(1,1))
    barplot(agg_table, main='Total emissions by year in Baltimore City')
}


# script block
# ###

# get data
df <- {
    dataobj <- createDataObject()
    dataobj$getData()
    dataobj$loadData()
}

# plot on screen device
doAssignement(df)

# plot on png device
png('plot2.png')
doAssignement(df)
dev.off()

# and... work finished better go for a walk
