# functions definition block
# ###

# creates an object to manipulate the data source/s
createDataObject <- function(basedir='data') {

    url <- 'http://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip'

    keyfiles <- list(
        datafile       = sprintf('%s/data.zip', basedir),
        summary        = sprintf('%s/summarySCC_PM25.rds', basedir),
        classification = sprintf('%s/Source_Classification_Code.rds', basedir),
        processed      = sprintf('%s/processed.rds', basedir)
    )

    # get and transform the data if necessary
    getData <- function(...) {

        if (!all(file.exists(unlist(keyfiles)))) {

            if (file.exists(basedir)) {
                unlink(basedir, recursive=T)
            }

            dir.create(basedir)
            download.file(url, keyfiles$datafile, ...)
            unzip(keyfiles$datafile, exdir=basedir)

            summary <- readRDS(keyfiles$summary)[,-3]
            classif <- readRDS(keyfiles$classification)

            coal_combustion_filter <-
                grepl('Combustion', classif$SCC.Level.One) &
                grepl('Coal', classif$SCC.Level.Three)

            vehicle_filter <- grepl('Vehicle', classif$SCC.Level.Two)

            my_classif <- data.frame(
                SCC = classif$SCC,
                is_coal_combustion = coal_combustion_filter,
                is_motor_vehicle = vehicle_filter)

            processed <- merge(summary, my_classif)
            processed$fips <- as.integer(processed$fips)
            processed$type <- factor    (processed$type)

            saveRDS(processed[,-1], file=keyfiles$processed)
        }

        return(0)
    }

    # read processed data generated by getData
    loadData <- function() {
        data <- readRDS(keyfiles$processed)
        return(data)
    }

    list(getData = getData, loadData = loadData)
}

# do the plotting work
doAssignement <- function(data) {

    agg_data1 <- data[data$is_motor_vehicle & data$fips %in% c(24510), c('Emissions', 'year', 'fips')]
    agg_data1 <- aggregate(agg_data1$Emissions / 1e3, list(agg_data1$year, agg_data1$fips), sum)
    agg_data1$x <- append(0, diff(agg_data1$x))

    agg_data2 <- data[data$is_motor_vehicle & data$fips %in% c(6037), c('Emissions', 'year', 'fips')]
    agg_data2 <- aggregate(agg_data2$Emissions / 1e3, list(agg_data2$year, agg_data2$fips), sum)
    agg_data2$x <- append(0, diff(agg_data2$x))

    agg_data <- rbind(agg_data1, agg_data2)
    colnames(agg_data) <- c('Year', 'Fips', 'Emissions')

    agg_data$Fips <- factor(agg_data$Fips, labels=c("Los Angeles County", "Baltimore City"))

    library(ggplot2)
    obj <- qplot(Year, Emissions, data=agg_data, geom="line", color=Fips,
                 main='Variation of Emissions',
                 xlab='Year',
                 ylab='Emissions (thousands)')
    print(obj)
}


# script block
# ###

# get data
df <- {
    dataobj <- createDataObject()
    dataobj$getData()
    dataobj$loadData()
}

# plot on screen device
doAssignement(df)

# plot on png device
png('plot6.png')
doAssignement(df)
dev.off()

# and... work finished better go for a walk
